/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkUpdateOfferRequest {
  offerExchange?: boolean;
  offerFreebie?: boolean;
  offerPayed?: boolean;
  stickerIds?: Array<number>;
}
