/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CardOfferResponse {
  id?: number;
  isReserved?: boolean;
  offerExchange?: boolean;
  offerFreebie?: boolean;
  offerPayed?: boolean;
  stickerId?: number;
  stickerName?: string;
}
