/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CardOfferRequest {
  offerExchange?: boolean;
  offerFreebie?: boolean;
  offerPayed?: boolean;
  stickerId?: number;
}
