/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateExchangeRequestDto {
  exchangeType?: 'EXCHANGE' | 'PAYED' | 'FREEBIE';
  offeredStickerId?: number;
  offererId?: number;
  requestedStickerId?: number;
}
