/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExchangeRequestDto {
  cancellationReason?: 'REQUESTER_CANCELED' | 'OFFERER_CANCELED' | 'OFFERED_CARD_REMOVED_BY_USER' | 'SEARCH_CARD_REMOVED_BY_USER';
  createdAt?: string;
  exchangeType?: 'EXCHANGE' | 'PAYED' | 'FREEBIE';
  id?: number;
  offeredStickerId?: number;
  offererClosed?: boolean;
  offererId?: number;
  partnerContact?: string;
  partnerFirstname?: string;
  partnerLastname?: string;
  requestedStickerId?: number;
  requestedStickerName?: string;
  offeredStickerName?: string;
  requesterClosed?: boolean;
  requesterId?: number;
  status?: 'INITIAL' | 'MAIL_SEND' | 'EXCHANGE_INTERREST' | 'EXCHANGE_COMPLETED' | 'EXCHANGE_CANCELED';
  updatedAt?: string;
}
