/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request to initiate password reset process
 */
export interface ForgotPasswordRequest {

  /**
   * Username or email address
   */
  identifier: string;
}
