/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatchResponse } from '../models/match-response';
import { PageableObject } from '../models/pageable-object';
import { SortObject } from '../models/sort-object';
export interface PageMatchResponse {
  content?: Array<MatchResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
