/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  contact?: string;
  firstname: string;
  lastname: string;
  mail: string;
  password: string;
  username: string;
  validationCode: string;
}
