/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request to reset password using a valid token
 */
export interface ResetPasswordRequest {

  /**
   * New password (minimum 8 characters)
   */
  newPassword: string;

  /**
   * Password reset JWT token
   */
  token: string;
}
