/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CardOfferStatistics } from '../models/card-offer-statistics';
import { CardSearchStatistics } from '../models/card-search-statistics';
export interface StatisticsResponse {
  cardOffers?: CardOfferStatistics;
  cardSearches?: CardSearchStatistics;
}
