/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkUpdateOfferRequest } from '../../models/bulk-update-offer-request';
import { CardOfferResponse } from '../../models/card-offer-response';

export interface UpdateBulkOffers$Params {
      body: BulkUpdateOfferRequest
}

export function updateBulkOffers(http: HttpClient, rootUrl: string, params: UpdateBulkOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CardOfferResponse>>> {
  const rb = new RequestBuilder(rootUrl, updateBulkOffers.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CardOfferResponse>>;
    })
  );
}

updateBulkOffers.PATH = '/api/card-offers/bulk';
