CREATE TABLE card_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sticker_id BIGINT NOT NULL,
    CONSTRAINT fk_card_searches_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_card_searches_sticker FOREIGN KEY (sticker_id) REFERENCES stickers (id)
);
