ALTER TABLE card_offers DROP COLUMN offer_type;

ALTER TABLE card_offers ADD COLUMN offer_payed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE card_offers ADD COLUMN offer_freebie BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE card_offers ADD COLUMN offer_exchange BOOLEAN NOT NULL DEFAULT FALSE;
