/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CardSearchRequest } from '../../models/card-search-request';
import { CardSearchResponse } from '../../models/card-search-response';

export interface AddSearch$Params {
      body: CardSearchRequest
}

export function addSearch(http: HttpClient, rootUrl: string, params: AddSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<CardSearchResponse>> {
  const rb = new RequestBuilder(rootUrl, addSearch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CardSearchResponse>;
    })
  );
}

addSearch.PATH = '/api/card-searches';
