/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CardSearchResponse } from '../../models/card-search-response';

export interface GetSearches$Params {
}

export function getSearches(http: HttpClient, rootUrl: string, params?: GetSearches$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CardSearchResponse>>> {
  const rb = new RequestBuilder(rootUrl, getSearches.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CardSearchResponse>>;
    })
  );
}

getSearches.PATH = '/api/card-searches';
