/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateExchangeRequestDto } from '../../models/create-exchange-request-dto';
import { ExchangeRequest } from '../../models/exchange-request';

export interface CreateExchangeRequest$Params {
      body: CreateExchangeRequestDto
}

export function createExchangeRequest(http: HttpClient, rootUrl: string, params: CreateExchangeRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<ExchangeRequest>> {
  const rb = new RequestBuilder(rootUrl, createExchangeRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExchangeRequest>;
    })
  );
}

createExchangeRequest.PATH = '/api/exchanges';
