/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExchangeRequestDto } from '../../models/exchange-request-dto';

export interface GetReceivedOffers$Params {
}

export function getReceivedOffers(http: HttpClient, rootUrl: string, params?: GetReceivedOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ExchangeRequestDto>>> {
  const rb = new RequestBuilder(rootUrl, getReceivedOffers.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ExchangeRequestDto>>;
    })
  );
}

getReceivedOffers.PATH = '/api/exchanges/received';
