/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageMatchResponse } from '../../models/page-match-response';

export interface GetExchangeMatches$Params {
  pageable: Pageable;
}

export function getExchangeMatches(http: HttpClient, rootUrl: string, params: GetExchangeMatches$Params, context?: HttpContext): Observable<StrictHttpResponse<PageMatchResponse>> {
  const rb = new RequestBuilder(rootUrl, getExchangeMatches.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageMatchResponse>;
    })
  );
}

getExchangeMatches.PATH = '/api/matches/exchange';
